# Use a Node.js image for building the client
FROM node:18 as build

WORKDIR /app
COPY ./client/package.json ./client/package-lock.json ./
RUN npm install
COPY ./client/ ./
RUN npm run build

# Production image
FROM nginx:alpine

# Copy the built React app
COPY --from=build /app/build /usr/share/nginx/html

# Copy your NGINX configuration for production if needed
COPY ./nginx.prod.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]