version: '3'

services:
  client:
    container_name: sonophile-client
    build:
      context: ./
      dockerfile: Dockerfile.prod
    environment:
      - VITE_API_URL=https://sonophile.xyz 
    ports:
      - "80:80"  # Expose port 80 for HTTP
      - "443:443"  # Expose port 443 for HTTPS
    volumes:
      - /home/ubuntu/certs:/etc/nginx/certs 

  server:
    container_name: sonophile-server
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - REDIRECT_URI=https://sonophile.xyz/api/callback
      - FRONTEND_URI=https://sonophile.xyz
      - MONGO_URI=${MONGO_URI}
